community/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/%', views.login, name='login'),
    # path('accounts/logout/%', views.logout, name='logout'),
    path('', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('practice/', views.practice, name='practice'),
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('post/', views.post_list, name='post_list'),
    # path('post/<int:upk>/', views.post_list, name='post_list'),

    path('post/new/', views.post_new, name='post_new'),
    path('post/theme_new/', views.theme_new, name='theme_new'),
    path('post/<str:theme>/delete/', views.theme_delete, name='theme_delete'),
    path('post/<str:theme>/change/', views.theme_change, name='theme_change'),
    path('post/<str:theme>/', views.post_list_theme, name='post_list_theme'),
    path('post/<str:theme>/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<str:theme>/<int:pk>/delete/',views.post_delete,name='post_delete'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/practice', views.post_practice, name='post_practice')
]

news/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Theme(models.Model):
    theme_title = models.CharField(max_length=50)
    TYPE_CHOICES = (('ST', 'Sub_theme'),('MT', 'Main_theme'))
    theme_type = models.CharField(max_length=20, choices=TYPE_CHOICES, default=TYPE_CHOICES[0]) #0이면 sub_theme, 1이면 main_theme

    def __str__(self):
        return str(str(self.theme_title) + " /  "+str(self.theme_type))

class Post(models.Model):
    #post된 news들

    title = models.CharField(max_length=200)
    text = models.TextField()
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, null=True, blank=True)
    temp_theme = models.CharField(max_length=50, null=True, blank=True)
    author = models.CharField(max_length=200)

    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    prating = models.ManyToManyField(User, through='Rating', default=None)
    #없는 값을 default 0하는게 맞나?

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.title)



#필요 없다.
class Recommand(models.Model):
    #추천하는 기사들
    recomm_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    recomm_post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return str(str(self.recomm_user) + " / "+str(self.recomm_post))

class Rating(models.Model):
    rating_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rating_users', null=True) # 현재 사용자
    rating_post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    # on_delete = models.CASADE 는 foreign key 가 삭제되면 이걸 들고 있는 데이터가 싹 사라짐

    GRADE_CHOICES = ((1, '1'), (2, '2'), (3,'3'), (4,'4'), (5,'5'))
    rating_grade = models.IntegerField(choices=GRADE_CHOICES, default=GRADE_CHOICES[4]) #get_rating_grade_disply로 html에서 볼 수 있음
    rating_direct = models.BooleanField(default=False)
    rating_date = models.DateTimeField(default=timezone.now)
    rating_grade_expect = models.FloatField(default=None, null=True, blank=True)
    
    #필요 없을듯
    def rating_save(self):
        self.save()

    def __str__(self):
        return str(str(self.rating_user) + " / " +str(self.rating_post) +" : "+ str(self.rating_grade))

news/forms.py
from django import forms
from .models import Post, Rating, Recommand, Theme

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','theme','temp_theme','author')

class RatingForm(forms.ModelForm):

    class Meta:
        model = Rating
        fields = ('rating_grade',)

class RecommandForm(forms.ModelForm):

    class Meta:
        model = Recommand
        fields = ('recomm_user','recomm_post',)

class ThemeForm(forms.ModelForm):

    class Meta:
        model = Theme
        fields = ('theme_title', 'theme_type',)

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Rating, Theme
from django.utils import timezone
from .forms import PostForm, RatingForm, ThemeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib import auth
from math import sqrt,pow

# Create your views here.
def mainpage(request):
    return render(request, 'registration/mainpage.html', {})

def practice(request, Loginf):
    return render(request, 'news/parctice.html', {'Loginf':Loginf})

@csrf_exempt
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('post_list')
        else:
            return render(request, 'registration/login.html', {'error':'username or password is incorrect'})
    return render(request, 'registration/login.html')

def register(request):
    if request.method == "POST":  # 무언가 받아왔을때
        try :
            user = User.objects.create_user(username=request.POST["username"], password=request.POST["password"])
            auth.login(request, user)
            return redirect('post_list')
        except:
            error = "id is already exist"
            return render(request, 'registration/register.html', {'error':error})

    return render(request, 'registration/register.html')

@login_required
def logout(request):
    auth.logout(request)
    return redirect('mainpage')

@login_required
def post_list(request):

    recommands_pk_list = []
    recommands_pk_list_prefer = []
    recommands_pk_list_disprefer = []
    controversial_pk_list = []
    print(Post.objects.count())
    if Post.objects.count() != 0 :
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        main_themes = Theme.objects.filter(theme_type='MT')
        sub_themes = Theme.objects.filter(theme_type='ST')
        recommands, controversials = rating_expectation(request)
        if len(recommands) != 0:
            for i in recommands:
                recommands_pk_list.append(i[1])
            if len(recommands_pk_list) > 3:
                recommands_pk_list_prefer = recommands_pk_list[2:]
                recommands_pk_list_disprefer = recommands_pk_list[:2]
            else:
                recommands_pk_list_prefer = recommands_pk_list[2:]
                recommands_pk_list_disprefer = []

        if len(controversials) != 0:
            for i in controversials:
                controversial_pk_list.append(i[0])
        return render(request, 'news/post_list.html', {'posts':posts,'main_themes':main_themes, 'sub_themes':sub_themes,
                                                       'recommands_prefer':recommands_pk_list_prefer,
                                                       'recommands_disprefer':recommands_pk_list_disprefer,
                                                       'recommands_controversial':controversial_pk_list})
    else:
        return render(request, 'news/post_list.html', {'posts':[],'main_themes':[], 'sub_themes':[],
                                                       'recommands_prefer':recommands_pk_list_prefer,
                                                       'recommands_disprefer':recommands_pk_list_disprefer,
                                                       'recommands_controversial':controversial_pk_list})
@login_required
def post_list_theme(request, theme='All'):
    print("theme : ",theme, type(theme))
    #theme에 포함된 글만 보여주는 것
    recommands_pk_list = []
    recommands_pk_list_prefer = []
    recommands_pk_list_disprefer = []
    controversial_pk_list = []
    
    if Theme.objects.count() == 0:
        #Theme이나 post가 없거나, theme을 받아온 경우가 아니라면
        print("theme 0")
        return render(request, 'news/post_list.html',
                      {'posts': [], 'main_themes': [], 'sub_themes':[],
                       'recommands_prefer': recommands_pk_list_prefer,
                       'recommands_disprefer': recommands_pk_list_disprefer,
                       'recommands_controversial': controversial_pk_list}
                      )
    elif Post.objects.count() == 0:
        print("post 0")
        main_themes = Theme.objects.filter(theme_type='MT')
        sub_themes = Theme.objects.filter(theme_type='ST')
        return render(request, 'news/post_list.html',
                      {'posts': [], 'main_themes': main_themes, 'sub_themes': sub_themes,
                       'recommands_prefer': recommands_pk_list_prefer,
                       'recommands_disprefer': recommands_pk_list_disprefer,
                       'recommands_controversial': controversial_pk_list}
                      )
    elif theme=='All':
        print("theme not 0, post not 0")
        posts = Post.objects.all().order_by('-published_date')
        main_themes = Theme.objects.filter(theme_type='MT')
        sub_themes = Theme.objects.filter(theme_type='ST')
        recommands, controversials = rating_expectation(request)
        if len(recommands) != 0:
            for i in recommands:
                recommands_pk_list.append(i[1])
            if len(recommands_pk_list) > 3:
                recommands_pk_list_prefer = recommands_pk_list[2:]
                recommands_pk_list_disprefer = recommands_pk_list[:2]
            else:
                recommands_pk_list_prefer = recommands_pk_list[2:]
                recommands_pk_list_disprefer = []

        if len(controversials) != 0:
            for i in controversials:
                controversial_pk_list.append(i[0])
        return render(request, 'news/post_list.html',
                      {'posts': posts, 'main_themes': main_themes, 'sub_themes': sub_themes,
                       'recommands_prefer': recommands_pk_list_prefer,
                       'recommands_disprefer': recommands_pk_list_disprefer,
                       'recommands_controversial': controversial_pk_list})
    else:
        #theme이 All이 아닐 경우
        theme_obj = Theme.objects.get(theme_title = theme)
        posts = []
        main_themes = Theme.objects.filter(theme_type='MT')
        sub_themes = Theme.objects.filter(theme_type='ST')
        if Post.objects.filter(theme=theme_obj).count() != 0:
            posts = Post.objects.filter(theme=theme_obj).order_by('-published_date')
        recommands, controversials = rating_expectation(request)
        if len(recommands) != 0:
            for i in recommands:
                recommands_pk_list.append(i[1])
            if len(recommands_pk_list) > 3:
                recommands_pk_list_prefer = recommands_pk_list[2:]
                recommands_pk_list_disprefer = recommands_pk_list[:2]
            else:
                recommands_pk_list_prefer = recommands_pk_list[2:]
                recommands_pk_list_disprefer = []

        if len(controversials) != 0:
            for i in controversials:
                controversial_pk_list.append(i[0])
        return render(request, 'news/post_list.html',
                          {'posts': posts, 'main_themes': main_themes, 'sub_themes':sub_themes,
                           'recommands_prefer': recommands_pk_list_prefer,
                           'recommands_disprefer': recommands_pk_list_disprefer,
                           'recommands_controversial': controversial_pk_list})
    


@login_required
def post_practice(request):
    now_user = request.user
    return render(request, 'news/practice.html', {'now_user':now_user})

@login_required
def rating_expectation(request):

    users = User.objects.filter()
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')  # 전체 posts
    critics={}
    posts_grade = {}
    for i in users:
        critics[i] ={}
        for j in posts:
            user_post_grade = Rating.objects.filter(rating_user=i,rating_post=j,rating_direct=True) #.get을 썼어도 됬는데.
            if len(user_post_grade) != 0:
                critics[i][j] = user_post_grade[0].rating_grade
                if j in posts_grade: #posts_grade 에 j라는 키가 있다면
                    posts_grade.get(j).append(user_post_grade[0].rating_grade)
                else:
                    temp = []
                    temp.append(user_post_grade[0].rating_grade)
                    posts_grade[j] = temp
    print("critics : " ,critics)
    recomm_list = getRecommendation(critics, users[request.user.pk-1])
    dispersion_list = getDispersion(posts_grade)

    return recomm_list, dispersion_list

def getDispersion(data, index=2):
    li=[]
    new_data= {}

    for i in data:
        vsum = 0
        avg_d = sum(data[i])/len(data[i])
        for j in data[i]:
            vsum = vsum + (j-avg_d)**2
        var = vsum/ len(data[i])
        new_data[i] = var
    li = new_data
    li = sorted(li.items(), key=(lambda x: x[1]), reverse = True)
    return li[:index]

def sim_distance(data, name1, name2):
    sum = 0
    for i in data[name1]:
        if i in data[name2]:  # 같은 영화를 봤다면
            sum += pow(data[name1][i] - data[name2][i], 2)
    return 1 / (1 + sqrt(sum))

def top_match(data, name, index=3, sim_function=sim_distance):
    li = []
    for i in data:
        if name != i:  # 자기 자신은 제외한다
            li.append((sim_function(data, name, i), i))  # 유사도, 이름을 튜플에 묶어 리스트에 추가한다
    # print(li)
    li.sort(key=lambda t: t[0])  # 오름차순 정렬
    li.reverse()  # 내림차순 정렬

    return li

def getRecommendation(data, person, sim_function=sim_distance):
    result = top_match(data, person, len(data))

    simSum = 0  # 유사도 합을 위한 변수
    score = 0  # 평점 합을 위한 변수
    li = []  # 리턴을 위한 리스트
    score_dic = {}  # 유사도 총합을 위한 dic
    sim_dic = {}  # 평점 총합을 위한 dic
    print(result)
    for sim, name in result:  # 튜플이므로 한번에

news/templates/news/base.html
{% load static %}
<html>
    <head>
        <title>news rec</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/news.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_superuser %}
                <h1><a href="/post">news rec - to post </a>

                <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="{% url 'theme_new' %}" class="top-menu"><span class="glyphicon glyphicon-info-sign"></span></a>
                <a href="{% url 'logout' %}" class="top-menu">Logout</a>
                <a href="/post" class="top-menu">{{user.username}}</a></h1>
            {% elif user.is_authenticated %}
                <h1><a href="/post">news rec - to post </a>

                <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="{% url 'theme_new' %}" class="top-menu"><span class="glyphicon glyphicon-info-sign"></span></a>
                <a href="{% url 'logout' %}" class="top-menu">Logout</a>
                <a href="/post" class="top-menu">{{user.username}}</a></h1>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-log-in"></span></a>
                <h1><a href="/">news rec - to login</a></h1>
            {% endif %}
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

news/templates/news/post_detail.html
{% extends 'news/base.html' %}

{% block content %}
    <div class="post">
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class = "btn btn-default" href="{% url 'post_delete' theme=post.theme.theme_title pk=post.pk%}">
            <span class="glyphicon glyphicon-remove-circle"></span></a>
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
                {{ post.author }}
                {{ post.theme.theme_title }}
            </div>
        {% endif %}


        <h1>{{ post.title }}</h1>
        <br>
        <p>{{ post.text|linebreaksbr }}</p>
        <form method="POST" class="rating-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">rate_save</button>
        </form>



    </div>
{% endblock %}

news/templates/news/post_edit.html
{% extends 'news/base.html' %}

{% block content %}
    <h1>post register</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

news/templates/news/post_list.html
{% extends 'news/base.html' %}


{% block content %}
<!--<script type="text/javascript">-->

<!--function all_s() {-->
        <!--var postA = document.getElementsByClassName("A"); -->
        <!--var postP = document.getElementsByClassName("P");-->
        <!--var postT = document.getElementsByClassName("T");   -->
        <!--for( var i = 0; i < postA.length; i++ ){ -->
            <!--var a = postA.item(i); -->
            <!--a.style.display = "block";-->
            <!--}-->

        <!--for(i = 0; i < postP.length; i++ ){ -->
            <!--var a = postP.item(i); -->
            <!--a.style.display =  "block";-->
        <!--}-->

        <!--for(i = 0; i < postT.length; i++ ){ -->
            <!--var a = postT.item(i); -->
            <!--a.style.display =  "block";-->
        <!--}-->
    <!--}-->
    <!---->

    <!--function all_h() {-->
        <!--var postA = document.getElementsByClassName("A"); -->
        <!--var postP = document.getElementsByClassName("P");-->
        <!--var postT = document.getElementsByClassName("T");   -->
        <!--for( var i = 0; i < postA.length; i++ ){ -->
            <!--var a = postA.item(i); -->
            <!--a.style.display = "none";-->
            <!--}-->

        <!--for(i = 0; i < postP.length; i++ ){ -->
            <!--var a = postP.item(i); -->
            <!--a.style.display =  "none";-->
        <!--}-->

        <!--for(i = 0; i < postT.length; i++ ){ -->
            <!--var a = postT.item(i); -->
            <!--a.style.display =  "none";-->
        <!--}-->
    <!--}-->
    <!---->
    <!--//숨기기-->
    <!--function hide_and_show(str) {-->
        <!--all_h();-->
        <!--var postA = document.getElementsByClassName(str); -->
        <!--for( var i = 0; i < postA.length; i++ ){ -->
            <!--var a = postA.item(i); -->
            <!--a.style.display = "block";-->
        <!--}-->

    <!--}-->

<!--</script>-->
   <!---->
<!--<p id= 'button area'>-->
    <!--<input type="button" value="All" onclick="all_s();"/>-->
    <!--<input type="button" value="Political" onclick="hide_and_show('P');"/>-->
    <!--<input type="button" value="Entertainment" onclick="hide_and_show('A');"/>-->
    <!--<input type="button" value="Tech" onclick="hide_and_show('T');"/>-->
<!--</p>-->

<p>
    <div> Main-Theme :
    {% for theme in main_themes %}
        <a href="{% url 'post_list_theme' theme=theme.theme_title %}">{{ theme.theme_title }}</a>
    {% endfor %}
    </div>
</p>
<p>
    <div> Sub-Theme :
    {% for theme in sub_themes %}
        <a href="{% url 'post_list_theme' theme=theme.theme_title %}">{{ theme.theme_title }}</a>
    {% endfor %}
    </div>
</p>

    <div class = "left-box">
        {% for post in posts %}
        <div class = "{{post.type}}" style="display: block;">
            <div class="post">
                <div class="date">
                    {{ post.published_date }}
                    {{ post.author }}
                    {{ post.theme.theme_title }}
                </div>
                <h1><a href="{% url 'post_detail' pk=post.pk theme=post.theme.theme_title %}">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaksbr|truncatewords:20 }}</p>
            </div>
        </div>
        {% endfor %}

    </div>
    <div class = "right-box">
        <h2>-you might prefer-</h2>
        {% for recommand in recommands_prefer %}
            <div class="post">
                <h3><a href="{% url 'post_detail' theme=recommand.theme.theme_title pk=recommand.pk %}">{{ recommand.title }}</a></h3>
            </div>
        {% endfor %}
        <h2>-you might haven't seen-</h2>
        {% for recommand in recommands_disprefer %}
            <div class="post">
                <h3><a href="{% url 'post_detail' theme=recommand.theme.theme_title pk=recommand.pk %}">{{ recommand.title }}</a></h3>
            </div>
        {% endfor %}
        <h2>-the most controversial-</h2>
        {% for recommand in recommands_controversial %}
            <div class="post">
                <h3><a href="{% url 'post_detail' theme=recommand.theme.theme_title pk=recommand.pk %}">{{ recommand.title }}</a></h3>
            </div>
        {% endfor %}
    </div>

{% endblock %}

news/templates/news/practice.html
{% extends 'news/base.html' %}

{% block content %}
    <a>oh my</a>
{% endblock %}

news/templates/news/theme_edit.html
{% extends 'news/base.html' %}

{% block content %}
    <h1>theme register</h1>
    {{ error }}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    <h2>theme delete button</h2>
    {% for theme in themes %}
        <p><a href="{% url 'theme_delete' theme=theme.theme_title %}">{{ theme.theme_title }}</a></p>
    {% endfor %}
    <h2>theme_type change button</h2>
    {% for theme in themes %}
        <p><a href="{% url 'theme_change' theme=theme.theme_title %}">{{ theme.theme_title }} - {{theme.get_theme_type_display}}</a></p>
    {% endfor %}
{% endblock %}